!     Fortran Parallel IO interface - Constants declaration

        INTEGER UNIFORM_CONTIGUOUS_READ, NONUNIFORM_CONTIGUOUS_READ, NONCONTIGUOUS_READ, EVERYONE_ENTIRE_DATASET_READ
		INTEGER UNIFORM_CONTIGUOUS_WRITE, NONUNIFORM_CONTIGUOUS_WRITE, NONCONTIGUOUS_WRITE 

        PARAMETER (UNIFORM_CONTIGUOUS_READ=0, NONUNIFORM_CONTIGUOUS_READ=1, NONCONTIGUOUS_READ=2, EVERYONE_ENTIRE_DATASET_READ=3)
		PARAMETER (UNIFORM_CONTIGUOUS_WRITE=4, NONUNIFORM_CONTIGUOUS_WRITE=5, NONCONTIGUOUS_WRITE=6)

        INTEGER FILE_CREATE, FILE_READONLY, FILE_READWRITE
        PARAMETER (FILE_CREATE=0, FILE_READONLY=1, FILE_READWRITE=2)

        INTEGER PIO_INTEGER, PIO_DOUBLE, PIO_FLOAT, PIO_LONG, PIO_CHAR, PIO_BYTE
        PARAMETER (PIO_INTEGER=0, PIO_DOUBLE=1, PIO_FLOAT=2, PIO_LONG=3, PIO_CHAR=4, PIO_BYTE=5)

