FROM ubuntu:bionic

ENV PETSC_DIR=/scratch/petsc PETSC_ARCH=petsc-arch
ARG PETSC_VERSION

RUN apt-get update -qq && \
    apt-get install -y git make cmake gcc gfortran g++ lcov \
                       python3 python3-h5py

WORKDIR /scratch
COPY ./.gitlab/build-petsc.sh .
RUN /scratch/build-petsc.sh

