ARG IMAGE
FROM $IMAGE
ENV PETSC_DIR=/scratch/petsc PETSC_ARCH=petsc-arch

ENV PFLOTRAN_DIR=/scratch
ENV SRC_DIR=$PFLOTRAN_DIR/src/clm-pflotran ARTIFACT_DIR=/tmp/test-pflotran-interface

WORKDIR $PFLOTRAN_DIR
COPY . .
RUN $PFLOTRAN_DIR/.gitlab/info.sh
RUN $PFLOTRAN_DIR/.gitlab/build-pflotran-interface.sh
RUN $PFLOTRAN_DIR/.gitlab/test-pflotran-interface.sh
